
DROP TABLE IF EXISTS PRODUCTEURFOURNISSEUR;
DROP TABLE IF EXISTS PRODUCTEURPOINTDEVENTE;
DROP TABLE IF EXISTS PRODUITPOINTDEVENTE;
DROP TABLE IF EXISTS PRODUITFOURNISSEUR;



DROP TABLE IF EXISTS PRODUIT;
DROP TABLE IF EXISTS FOURNISSEUR;

DROP TABLE IF EXISTS POINTDEVENTE;
DROP TABLE IF EXISTS PRODUCTEUR;


